drop database if exists Pruebas;
create database Pruebas;
use Pruebas;

create table Docentes(
    docente_id char(36) not null primary key,
    docente_nombre varchar(120),
    docente_mail varchar(120),
    docente_contrasena varchar(120)
);

create table Temarios (
    temario_id int not null primary key auto_increment,
    temario_nombre varchar(120)
);

create table Tipos (
    tipo_id int not null primary key auto_increment,
    tipo_nombre varchar(120)
);

create table Pruebas (
    prueba_id char(8) not null primary key,
    prueba_numero_preguntas integer,
    prueba_puntaje_promedio float,
    prueba_fecha datetime,
    temario_id int not null,
    docente_id varchar(120) not null,
    foreign key (temario_id) references Temarios(temario_id),
    foreign key (docente_id) references Docentes(docente_id)
);

create table Estudiantes (
    estudiante_id varchar(120) not null primary key,
    estudiante_nombre varchar(30),
    estudiante_puntaje int not null,
    prueba_id char(8) not null,
    foreign key (prueba_id) references Pruebas(prueba_id)
);

create table Preguntas (
    pregunta_id int not null primary key auto_increment,
    pregunta_imagen varchar(120),
    pregunta_pregunta varchar(120),
    pregunta_respuesta_correcta varchar(120),
    pregunta_respuesta_incorrecta varchar(120),
    temario_id int not null,
    tipo_id int not null,
    foreign key (temario_id) references Temarios(temario_id),
    foreign key (tipo_id) references Tipos(tipo_id)
);

create table PruebasxPreguntas (
    pruebasxPreguntas_id int not null primary key auto_increment,
    prueba_id char(8) not null,
    pregunta_id int not null,
    foreign key (prueba_id) references Pruebas(prueba_id),
    foreign key (pregunta_id) references Preguntas(pregunta_id)
);

insert into Tipos (tipo_nombre) values ("tipo 1");

insert into Temarios (temario_nombre) values ("Animales");
insert into Temarios (temario_nombre) values ("Colores");
insert into Temarios (temario_nombre) values ("Numeros");
insert into Temarios (temario_nombre) values ("Partes del cuerpo");
insert into Temarios (temario_nombre) values ("Preguntas simples");
insert into Temarios (temario_nombre) values ("Presente simple verbos");
insert into Temarios (temario_nombre) values ("Verbos to be");
insert into Temarios (temario_nombre) values ("Do does");

INSERT INTO Preguntas (pregunta_pregunta, pregunta_imagen, pregunta_respuesta_correcta, pregunta_respuesta_incorrecta, temario_id, tipo_id) VALUES 
("cabra ", "goat", "goat", "walrus", 1, 1),
("camello ", "camel", "camel", "seal", 1, 1),
("cangrejo ", "crab", "crab", "rooster", 1, 1),
("castor", "beaver", "beaver", "raccoon", 1, 1),
("cebra", "zebra", "zebra", "rabbit", 1, 1),
("cerdo", "pig", "pig", "pig", 1, 1),
("cocodrilo ", "crocodile", "crocodile", "mouse", 1, 1),
("conejo", "rabbit", "rabbit", "monkey", 1, 1),
("delfin ", "dolphin", "dolphin", "lion", 1, 1),
("elefante", "elephant", "elephant", "horse", 1, 1),
("foca", "seal", "seal", "hippopotamus", 1, 1),
("gallo", "rooster", "rooster", "hedgehog", 1, 1),
("gato", "cat", "cat", "goat", 1, 1),
("girafa", "giraffe", "giraffe", "giraffe", 1, 1),
("hipopotamo", "hippopotamus", "hippopotamus", "fox", 1, 1),
("leon", "lion", "lion", "fish", 1, 1),
("mapache", "raccoon", "raccoon", "elephant", 1, 1),
("mono", "monkey", "monkey", "duck", 1, 1),
("morsa", "walrus", "walrus", "dolphin", 1, 1),
("pato ", "duck", "duck", "dog", 1, 1),
("perro ", "dog", "dog", "crab", 1, 1),
("pez", "fish", "fish", "cow", 1, 1),
("pollo", "chicken", "chicken", "chicken", 1, 1),
("puercoespin ", "hedgehog", "hedgehog", "cat", 1, 1),
("raton", "mouse", "mouse", "camel", 1, 1),
("vaca ", "cow", "cow", "beaver", 1, 1),
("zorro", "fox", "fox", "crocodile", 1, 1),
("caballo", "horse", "horse", "camel", 1, 1),
("cebra", "zebra", "zebra", "rabbit", 1, 1),
("foca", "seal", "seal", "hippopotamus", 1, 1),
("What color is the sky on a clear day?", "Blue", "Blue", "Green", 2, 1),
("What color is grass?", "Green", "Green", "Purple", 2, 1),
("What color is a ripe apple?", "Red", "Red", "Blue", 2, 1),
("What color is the sun?", "Yellow", "Yellow", "Pink ", 2, 1),
("What color are the leaves on a tree in the fall?", "Brown", "Brown", "Red", 2, 1),
("What color is chocolate?", "Brown", "Brown", "Purple", 2, 1),
("What color is the sky at sunset? ", "Orange", "Orange", "Blue", 2, 1),
("What color is a rainbow?", "Multicolored", "Multicolored", "Black", 2, 1),
("What color is the earth?", "Brown", "Brown", "Pink", 2, 1),
("What color are ripe bananas?", "Yellow", "Yellow", "Red", 2, 1),
("What color is lavender? ", "Purple", "Purple", "Orange", 2, 1),
("What color are clouds on a gray day? ", "Gray", "Gray", "Pink", 2, 1),
("What color are ripe tomatoes? ", "Red", "Red", "Yellow", 2, 1),
("What color is watermelon? ", "Green with red stripes ", "Green with red stripes ", "Blue", 2, 1),
("What color is fire? ", "Red/Orange", "Red/Orange", "Blue", 2, 1),
("What color is fog? ", "White/Gray ", "White/Gray ", "Red", 2, 1),
("What color is freshly mowed grass? ", "Dark Green", "Dark Green", "Yellow", 2, 1),
("What color is a ripe lemon? ", "Yellow", "Yellow", "Red", 2, 1),
("What color are sunflowers? ", "Yellow", "Yellow", "Orange", 2, 1),
("What color is the ocean on a clear day? ", "Blue", "Blue", "Green ", 2, 1),
("What color are ladybugs? ", "Red with black ", "Red with black ", "Green with yellow spots ", 2, 1),
("What color is a pumpkin? ", "Orange", "Orange", "Green", 2, 1),
("What color are red roses? ", "Red", "Red", "Yellow", 2, 1),
("What color are the leaves of a mint plant? ", "Green", "Green", "Brown", 2, 1),
("What color is the fur of a Dalmatian dog? ", "White with black ", "White with black ", "Black with white spots", 2, 1),
("What color is milk chocolate? ", "brown", "brown", "Green", 2, 1),
("Violeta", "Violet", "Violet", "Purple", 2, 1),
("Morado", "Purple", "Purple", "Violet", 2, 1),
("Oro", "Golden", "Golden", "Sylver", 2, 1),
("Plata", "Sylver", "Sylver", "Golden", 2, 1),
("one", "uno", "uno", "beinte", 3, 1),
("two", "dos", "dos", "catorse", 3, 1),
("three", "tres", "tres", "cinco", 3, 1),
("four", "cuatro", "cuatro", "cuatro", 3, 1),
("five", "cinco", "cinco", "diecinueve", 3, 1),
("six", "seis", "seis", "dieciseis", 3, 1),
("seven", "siete", "siete", "diecisiete", 3, 1),
("eight", "ocho", "ocho", "diesciocho", 3, 1),
("nine", "nueve", "nueve", "diez", 3, 1),
("ten", "diez", "diez", "doce", 3, 1),
("eleven", "once", "once", "dos", 3, 1),
("twelve", "doce", "doce", "nueve", 3, 1),
("thirteen", "trece", "trece", "ocho", 3, 1),
("fourteen", "catorse", "catorse", "once", 3, 1),
("fifteen", "quinse", "quinse", "quinse", 3, 1),
("sixteen", "dieciseis", "dieciseis", "seis", 3, 1),
("seventeen", "diecisiete", "diecisiete", "siete", 3, 1),
("eightteen", "diesciocho", "diesciocho", "trece", 3, 1),
("nineteen", "diecinueve", "diecinueve", "tres", 3, 1),
("twenty", "beinte", "beinte", "uno", 3, 1),
("Which body part do we use to see?", "Eyes", "Eyes", "Ears", 4, 1),
("What do we use to smell things?", "Nose", "Nose", "Mouth", 4, 1),
("Which part of the body do we use to taste food?", "Tongue", "Tongue", "Hand", 4, 1),
("What is the body part we use for hearing?", "Ears", "Ears", "Eyes", 4, 1),
("What is the name of the body part we use for eating?", "Mouth", "Mouth", "Foot", 4, 1),
("Which body part helps us to breathe?", "Lungs", "Lungs", "Stomach", 4, 1),
("What is the name of the body part we use for speaking?", "Mouth", "Mouth", "Knee", 4, 1),
("Which body part do we use for walking?", "Legs", "Legs", "Arms", 4, 1),
("What is the name of the body part we use for writing?", "Hand ", "Hand ", "Head", 4, 1),
("Which body part do we use for smelling flowers?", "Nose", "Nose", "Eyes", 4, 1),
("What is the name of the body part we use for tasting ice cream?", "Tongue", "Tongue", "Ear", 4, 1),
("Which body part helps us to see colors?", "Eyes", "Eyes", "Feet", 4, 1),
("What do we use to touch and feel things?", "Hands", "Hands", "Mouth", 4, 1),
("Which body part helps us to jump?", "Legs ", "Legs ", "Stomach", 4, 1),
("What is the name of the body part we use for hugging?", "Arms", "Arms", "Head", 4, 1),
("Which body part do we use for smiling?", "Mouth", "Mouth", "Knee", 4, 1),
("What is the name of the body part we use for running?", "Legs", "Legs", "Ears", 4, 1),
("Which body part helps us to listen to music?", "Ears", "Ears", "Eyes", 4, 1),
("What is the body part we use for clapping?", "Hands", "Hands", "Mouth", 4, 1),
("Which body part do we use for singing?", "Mouth", "Mouth", "Head", 4, 1),
("What is the name of the body part we use for kicking a ball?", "Foot", "Foot", "Nose", 4, 1),
("Which body part helps us to taste sweet and sour things?", "Tongue", "Tongue", "Hand", 4, 1),
("What do we use to smell delicious food?", "Nose", "Nose", "Eyes", 4, 1),
("Which body part helps us to see in the dark?", "Eyes", "Eyes", "Feet", 4, 1),
("What is the name of the body part we use for drawing?", "Hand", "Hand", "Head", 4, 1),
("Which body part do we use for dancing?", "Legs", "Legs", "Stomach", 4, 1),
("What is the name of the body part we use for waving goodbye?", "Hand", "Hand", "Ear", 4, 1),
("Which body part helps us to hear our favorite songs?", "Ears", "Ears", "Eyes", 4, 1),
("What is the body part we use for tasting ice cream?", "Tongue", "Tongue", "Foot", 4, 1),
("Which body part do we use for smelling yummy pizza?", "Nose", "Nose", "Mouth", 4, 1),
("dog runs. The", "The dog runs.", "The dog runs.", "The dog runs.", 5, 1),
("The dog rolls around.", "The dog rolls around.", "The dog rolls around.", "The dog rolls around.", 5, 1),
("The sits dog.", "The dog sits.", "The dog sits.", "The dog sits.", 5, 1),
("The dog bone. chews the ", "The dog chews the bone.", "The dog chews the bone.", "The dog chews the bone.", 5, 1),
("she ____ a bike", "rides ", "rides ", "ride", 5, 1),
("they ___ pizza", "Eat", "Eat", "eats", 5, 1),
("he ___ soccer", "plays", "plays", "play", 5, 1),
("i ____ ballet", "dance", "dance", "dances", 5, 1),
("it ___ watter", "drinks", "drinks", "drink", 5, 1),
("fish/eats/bear/the", "the bear eats fish", "the bear eats fish", "the fish eats bear", 5, 1),
("doesnt/the/eat/bear/winter/in", "the bear doesn�t eat in winter", "the bear doesn�t eat in winter", "the bear eat doesn�t in winter", 5, 1),
("the/does/climb/bear/trees/?", "does the bear climb trees?", "does the bear climb trees?", "the does bear climb trees?", 5, 1),
("he doesn�t have a teddy bear", "option 2", "option 2", "option 1", 5, 1),
("he has a car", "option 1", "option 1", "option 2", 5, 1),
("they have dolls", "option 1", "option 1", "option 2", 5, 1),
("i don�t have lots of shells", "option 2", "option 2", "option 1", 5, 1),
("mom and dad ___ the food", "buy", "buy", "buys", 5, 1),
("we ____ pictures in ours books", "draw", "draw", "draws", 5, 1),
("miss ___ the bell at lunch time", "rings", "rings", "ring", 5, 1),
("they ___ songs for us.", "sing", "sing", "sings", 5, 1),
("des and aleeka ___ the hands on the clock", "turn", "turn", "turns", 5, 1),
("many boys ___ to school", "walk", "walk", "walks", 5, 1),
("the driver ___ the wheel", "spins", "spins", "spin", 5, 1),
("both boys ___ really well.", "dance", "dance", "dances", 5, 1),
("What verb does the image belong to?", "sing", "sing", "dances", 5, 1),
("What verb does the image belong to?", "dance", "dance", "cook", 5, 1),
("What verb does the image belong to?", "cook", "cook", "listten to music", 5, 1),
("What verb does the image belong to?", "play the guitar", "play the guitar", "play soccer", 5, 1),
("What verb does the image belong to?", "listten to music", "listten to music", "write", 5, 1),
("What verb does the image belong to?", "play soccer", "play soccer", "wattch ttv", 5, 1),
("he ___ fountains", "builds", "builds", "build", 6, 1),
("kim ___ up fastly", "stands", "stands", "stand", 6, 1),
("adults __ everyday", "work", "work", "works", 6, 1),
("some animals ____", "climb", "climb", "climbs", 6, 1),
("eagles ______ highly", "fly", "fly", "flies", 6, 1),
("alan _____ videos", "watches", "watches", "watch", 6, 1),
("my friends _____ me", "visit ", "visit ", "visits", 6, 1),
("kids _____ chocolate", "love", "love", "loves", 6, 1),
("i ____ my dog", "feed", "feed", "feeds", 6, 1),
("you ____ a dress", "wear", "wear", "wears", 6, 1),
("this chef ____ cooking", "loves", "loves", "love", 6, 1),
("luis and i ____ a lot", "dance", "dance", "dances", 6, 1),
("they ____ to music", "listen", "listen", "listens", 6, 1),
("i ____ my room", "clean", "clean", "cleans", 6, 1),
("he ___ the dishes", "does", "does", "do", 6, 1),
("she ___ to bed late", "goes", "goes", "go", 6, 1),
("we ___ food", "buy", "buy", "buys", 6, 1),
("you ____ here", "sleep", "sleep", "sleeps", 6, 1),
("it ____ in the park", "runs", "runs", "run", 6, 1),
("they never ___ dinner", "cook", "cook", "cooks", 6, 1),
("emma and i ___ tv", "watch", "watch", "watches", 6, 1),
("the dog ____ with me", "walks", "walks", "walk", 6, 1),
("the kids ___ a lot", "play", "play", "plays", 6, 1),
("we___ the recorder flute", "practice", "practice", "practices", 6, 1),
("emily and tom ___", "sing", "sing", "sings", 6, 1),
("cats ____ mice", "chase", "chase", "chases", 6, 1),
("you ____ apples", "like", "like", "likes", 6, 1),
("mark ___ a shower", "takes", "takes", "take", 6, 1),
("this plant ____ fastly", "grows", "grows", "grow", 6, 1),
("my mom ___ math", "teaches", "teaches", "teach", 6, 1),
("I�___�from Texas.", "Am", "Am", "Are", 7, 1),
("Where�__�your sister today?", "Is", "Is", "Am", 7, 1),
("Those girls�___�really nice.", "Are", "Are", "Am", 7, 1),
("We __ very happy living in London.", "Are", "Are", "is", 7, 1),
("I�___ a teacher.", "Am", "Am", "is", 7, 1),
("What he says ___ true.", "Is", "Is", "Are", 7, 1),
("Who ___�your favorite pop starts?", "Are", "Are", "Is", 7, 1),
("This exercise ___ really difficult.", "Is", "Is", "Am", 7, 1),
("Paul and Tom __�my best friends.", "Are", "Are", "Am", 7, 1),
("Mary ___ a good friend of mine.", "is", "is", "Are", 7, 1),
("I ___ ready to go shopping.", "Am", "Am", "Are", 7, 1),
("Bulls ___ really dangerous.", "Are", "Are", "Am", 7, 1),
("is / She / an /person / intelligent", "She is an intelligent person", "She is an intelligent person", "She is intelligent an person", 7, 1),
("�is / round / This / table", "This table is round", "This table is round", "This round table is ", 7, 1),
("There / men / two / are / here", "There are two men here", "There are two men here", "There are two here men ", 7, 1),
("you / ready / Are ?", "Are you ready?", "Are you ready?", "You are ready?", 7, 1),
("�you / are / Where / from ?", "Where are you from?", "Where are you from?", "Where you are you from?", 7, 1),
("His father ____ sad.", "Is not", "Is not", "Are not", 7, 1),
("I ____ at home.", "Am not", "Am not", "Are not", 7, 1),
("�Peter and I ____ tired.", "Are not", "Are not", "Is not", 7, 1),
("It ____ a small house.", "Is not", "Is not", "Am not", 7, 1),
("Peter and Tom ___ bus drivers.", "Are not", "Are not", "Is not", 7, 1),
("Our new car ____ red.", "Is not", "Is not", "Are not", 7, 1),
("My uncle ____ in Japan.", "Is not", "Is not", "Are not", 7, 1),
("My grandmother __ 80 years old.", "Is not", "Is not", "Am not", 7, 1),
(" I ____ happy.", "Am not", "Am not", "Are not", 7, 1),
("She ____ my best friend.", "Is not", "Is not", "Am not", 7, 1),
(" I ____ a very good driver.", "Am", "Am", "Is", 7, 1),
("Susan and Mike ____ my parents.", "Are", "Are", "Am", 7, 1),
("Susan ____ my new friend.", "Is", "Is", "Are", 7, 1),
("____ she go fishing? Yes, she ___",	"Does, Does",	"Does, Does",	"Does, Does", 8, 1),
("_ she have many friends? No, she _",	"Does, Doesn't",	"Does, Doesn't",	"Doesn't, Does", 8, 1),
("_do they practise tennis? No, they _	", "Do, Don't", "Do, Don't", "Don't, Do", 8, 1),
("__ you play cards? No, i__",	"Do, Don't",	"Do, Don't",	"Don't, Do", 8, 1),
("__ she like biscuits? Yes, she __",	"Does, Does",	"Does, Does",	"Does, Does", 8, 1),
("__ he skip the rope? Yes, he",	"Does, Does",	"Does, Does",	"Does, Does", 8, 1),
("__ she walk to school? No, she", 	"Does, Doesn't", 	"Does, Doesn't", 	"Doesn't, Does", 8, 1),
("__ babies run? Yes, they __",	"Do, Don't",	"Do, Don't",	"Don't, Do", 8, 1),
("__ they grow flowers? Yes, they _",	"Do, Do",	"Do, Do",	"Do, Do", 8, 1),
("__ he play drums? Yes, he",	"Does, Does",	"Does, Does",	"Does, Does", 8, 1),
("__ they work in an office? No, they_",	"Do, Do",	"Do, Do",	"Do, Do", 8, 1),
("_ she water the plants? Yes, he __",	"Does, Does",	"Does, Does",	"Does, Does", 8, 1),
("__ giraffes bark? No, they __",	"Do, Do",	"Do, Do",	"Do, Do", 8, 1),
("__ she study hard? No, she __",	"Does, Doesn't",	"Does, Doesn't",	"Doesn't, Does", 8, 1),
("__ they get up early? Yes, they __",	"Do, Do",	"Do, Do",	"Do, Do", 8, 1),
("__ you play computer games? No, i",	"Do, Don't",	"Do, Don't",	"Doesn't, Do", 8, 1),
("__ i carry an apple? Yes, you __",	"Do, Do ",	"Do, Do ",	"Do, Do ", 8, 1),
("__ the dog eat its food? Yes, it __", "Does, Does ", "Does, Does ", "Does, Does ", 8, 1),
("you drink coffee?",	"Do",	"Do",	"Doesn't", 8, 1),
("he play table tennis?",	"Does",	"Does",	"Do", 8, 1),
("she skip at school?",	"Does",	"Does",	"Don't", 8, 1),
("they live in barcelona?",	"Do",	"Do",	"Don't", 8, 1),
("he ride a bike?	", "Does", "Does", "Do", 8, 1),
("you driver a car?",	"Do",	"Do",	"Does", 8, 1),
("she like apples?", 	"Does", 	"Do", 	"Does", 8, 1),
("you read books?",	"Do",	"Do",	"Don't", 8, 1),
("he write litters?",	"Does",	"Does",	"Do", 8, 1),
("she play the cymbals?",	"Does",	"Does",	"Don't", 8, 1),
("you live near the river?",	"Do",	"Do",	"Does", 8, 1),
("she eat vegetables? ",	"Does",	"Does",	"Don't", 8, 1);